#!/bin/bash

# This file is useful for development purposes because
# it allows you to run TypeScript files without having
# to add the --loader option every time.

# Usage:

# ./node --version
# ./node bootstrap/test.ts
# ./node --inspect bootstrap/test.ts

# Usage with "sh" or "bash":

# sh node --version
# sh node bootstrap/test.ts
# sh node --inspect bootstrap/test.ts

# Node.js executable with all arguments required to run the application.
node="node --loader ts-node/esm --experimental-import-meta-resolve --no-warnings"

$node $@
